// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/19/2026, 10:41:55 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/zeinab/projects/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeinab/projects/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeinab/projects/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeinab/projects/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeinab/projects/portfolio/plugins/**/*.{js,ts,mjs}","/home/zeinab/projects/portfolio/composables/**/*.{js,ts,mjs}","/home/zeinab/projects/portfolio/utils/**/*.{js,ts,mjs}","/home/zeinab/projects/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/zeinab/projects/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/zeinab/projects/portfolio/app.config.{js,ts,mjs}","/home/zeinab/projects/portfolio/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;